# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-react
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173 # Use 3000 if you're using CRA

