# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5173 # or 3000 for CRA
      nodePort: 30080 # this is the external port
